### ISSUE TITLE
zodToJsonSchema target

### ISSUE THREAD

**Issue by StefanTerdell** [MunifTanjim/express-zod-openapi#2]
Hello! Neat package. 

You might want to target the openApi3 specification instead of jsonSchema7 (which is default) though:
```ts
const result = zodToJsonSchema(schema, { target: "openApi3" });
```

**Comment by MunifTanjim** [comment]
Hey! Thanks for checking it out.

> You might want to target the openApi3 specification instead of jsonSchema7 (which is default) though:

![image](https://user-images.githubusercontent.com/8050659/169700103-08e049f9-c819-448b-9818-da22a8ac665b.png)


Setting `target: "openApi3"` makes the return type `object`. Is that intentional? 🤔

**Comment by StefanTerdell** [comment]
Kind of. The ability to target openApi3 was pretty much an after thought and I haven't spent any time creating the typings for it, neither did I want to add a dependency. However, the actual output should be sound.
